apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oke-fsspvc1
spec:
  storageClassName: oci-fss1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: oke-fsspv1
